import {StyleSheet} from "react-native";
import {colors,fontSize} from "../../../styles/defount.json"
let card_size = 50;
export default StyleSheet.create({
    container:{
        paddingRight:15
    },
    table_main:{
        marginTop:10,
        maxHeight:card_size,
        borderRadius:5,
        borderBottomWidth:2,
        borderColor:colors.blue_dark_opacity,
        overflow:"hidden",
        backgroundColor:colors.white
    },
    view_main:{
        justifyContent:"space-between",
        flexDirection:"row",
        borderBottomWidth:1,
        borderColor:colors.blue_opacity,
    },
    menu_wrap:{
        flexDirection:"row",
        maxWidth:101,
    },
    menu_hidded:{
        position:"absolute",
        backgroundColor:colors.white,
        right:"100%",
        top:0,
        flexDirection:"row",
    },
    btn:{
        height:card_size,
        width:card_size,
        justifyContent:"center",
        alignItems:'center',
        marginRight:1,
    },
    status_wrap:{
        height:card_size,
        minWidth:card_size,
        backgroundColor:colors.blue_opacity,
        justifyContent:"center",
        alignItems:'center',
        borderTopStartRadius:5,
    },
    btn_last:{
        borderTopEndRadius:5,
        marginRight:0,
    },
    white_color:{
        color:colors.white
    },
    btn_activete:{
        backgroundColor:colors.blue_opacity
    },
    not_link:{
        color:colors.black
    },
    red:{
        backgroundColor:colors.red,
    },
    orange:{
        backgroundColor:colors.orange,
    },
    green:{
        backgroundColor:colors.green,
    },
    blue:{
        backgroundColor:colors.secondary,
    },
    yellow:{
        backgroundColor:colors.yellow,
    },

    red_btn:{
        backgroundColor:colors.red_opacity,
        text:{
            color:colors.red
        }
    },
    orange_btn:{
        backgroundColor:colors.orange_opacity,
        text:{
            color:colors.orange
        }
    },
    green_btn:{
        backgroundColor:colors.green_opacity,
        text:{
            color:colors.green
        }
    },
    blue_btn:{
        backgroundColor:colors.blue_opacity,
        text:{
            color:colors.secondary
        }
    },
    yellow_btn:{
        backgroundColor:colors.yellow_opacity,
        text:{
            color:colors.yellow
        }
    },
    

    container_length:{
        paddingBottom:15,
        alignItems:"flex-start",
        marginTop:15
    },
    h2:{
        color:colors.black,
        fontSize:fontSize.p,
        opacity:.5,
        padding:0,
        margin:0,
        fontWeight:"bold",
    },
    icon:{
        width:25,
        height:25,
        color:colors.secondary,
    },
    content_main:{
        flex:1,
        justifyContent:"center",
        paddingHorizontal:10,
        height:card_size,
    },
    content_main_text:{
        color:colors.black,
        fontSize:fontSize.p,
        overflow:"hidden",
        fontWeight:"bold",
    },
    content_hidded:{
        padding:15,
    },
    text_wrap:{
        flexDirection:"row",
        flexWrap:"wrap",
    },
    text:{
        color:colors.accent_dark,
        fontWeight:"bold",
        fontSize:fontSize.p,
        marginLeft:15,
    },
    text_label:{
        opacity:.7,
        marginLeft:0,
    },
    to_rotate:{
        transform: [{ rotate: '0deg' }],
    },
    download_btn:{
        flex:1,
        width:"100%",
        alignItems: 'center',
        justifyContent: 'center',
    },
    status_text:{
        fontWeight:'bold',
        fontSize:fontSize.small,
        color:"#fff"
    }
})
