import {StyleSheet} from "react-native";
import {colors, fontSize} from "../../styles/defount.json"

export default StyleSheet.create({
    container:{
        paddingTop:5,
        paddingBottom:20,
        paddingHorizontal:15,
        flex:1,
        backgroundColor:colors.white,
        minHeight:450,
    },
    list_wrap:{
        marginBottom:5,
        borderBottomWidth:2,
        borderRightWidth:1,
        paddingHorizontal:5,
        paddingVertical:5,
        borderColor:"rgba(100, 100, 100,0.1)",
        backgroundColor:colors.primary,
        borderRadius:5,
        elevation:2,
    },
    text_wrap:{
        display:"flex",
        flexDirection: "row",
    },
    info:{
        display:"flex",
        justifyContent:"space-between",
        alignItems: "flex-start",
        flexDirection: "row",
    },
    h5:{
        color:colors.black,
        fontWeight:"bold",
        fontSize:fontSize.p,
    },
    h5_content:{
        opacity:0.7,
        minWidth:110,
        marginBottom:3
    },
    small:{
        color:colors.black,
        fontWeight:"bold",
        fontSize:fontSize.p,
        opacity:0.7,
    },
    status:{
        fontWeight:"bold",
        fontSize:fontSize.p
    },
    category:{
        color:colors.accent_dark,
        opacity:1,
    }, 
    green:{
        color:colors.green
    },
    red:{
        color:colors.red
    },
    orange:{
        color:colors.orange
    },
    dark_blue:{
        color:colors.accent
    },
    actions:{
        display:"flex",
        flexDirection: "row",
        justifyContent:"space-between",
        marginTop:5,
        alignItems:"flex-start",
    },
    icon:{
        height:25,
        width:25,
        color:colors.accent,
        marginRight:5,
        marginTop:2
    },///draggables styles

    draggables:{
        display:"flex",
        flexDirection:"row",
        backgroundColor:colors.primary,
    },
    draggable_container:{
        // position:"relative",
        width:350,
        backgroundColor:colors.white,
        marginRight:10,
        paddingHorizontal:10,
        borderRadius:5,
        minHeight:450,
        elevation:-10,
        height:"100%",
        zIndex:-10,
        paddingTop:5,
        // opacity:0.3
    },
    draggable_title:{
        marginBottom:20,
    },
    title_status:{
        fontSize:fontSize.label,
        fontWeight:"bold",
    },
    info_draggable:{
        justifyContent:"flex-start",
    },
    small_count:{
        fontSize:14
    },
    img_icon_wrap:{
        width:60,
        height:60,
        color:colors.black,
        opacity:0.3,
        marginRight:15,
        padding:2,
        borderRadius:30,
        borderWidth:2,
    },
    img_icon:{
        width:50,
        height:50,
        color:colors.black,
    },
    list_wrap_draggable:{
        position:"relative",
        paddingLeft:10,
        paddingTop:10,
        elevation:2,
        zIndex:2,
    },
    h5_seller:{
        fontSize:fontSize.label,
        paddingRight:60,
    },
    h4:{
        opacity:0.7,
        paddingRight:60,
    },
    msg_ico_wrap:{
        position:"absolute",
        top:-35,
    },
    icon_msg:{
        color:colors.green,
        marginRight:25,
    },
    msgs_count:{
        color:colors.green,
        position:"absolute",
        right:50,
        top:-5,
        fontSize:13
    },
    text_wrap_padding:{
        paddingRight:50,
    },

})